FROM python:3.12-slim

WORKDIR /app

COPY requirements/frontend.txt .

RUN pip install --no-cache-dir -r frontend.txt

COPY . .

CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501", "--server.address=0.0.0.0"]