services:

  # ==============================
  # BACKEND (API)
  # ==============================
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data_volume:/app/data
    ports:
      - "8000:8000"
    networks:
      - app_network

  # ==============================
  # FRONTEND (STREAMLIT)
  # ==============================
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend_app
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - data_volume:/app/data
    ports:
      - "8501:8501"
    networks:
      - app_network

  # ==============================
  # PIPELINE (ETL)
  # ==============================
  pipeline:
    build:
      context: .
      dockerfile: pipeline/Dockerfile
    container_name: pipeline_job
    env_file:
      - .env
    volumes:
      - data_volume:/app/data
    networks:
      - app_network

# ==============================
# REDE
# ==============================
networks:
  app_network:
    driver: bridge

# ==============================
# VOLUME (DADOS)
# ==============================
volumes:
  data_volume: