FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    python3-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/pipeline.txt .

RUN pip install --no-cache-dir -r pipeline.txt

COPY . .

CMD ["python", "rodar_pipeline.py"]