FROM python:3.12-slim

WORKDIR /app

# dependências de build (pyreaddbc)
RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    python3-dev \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# poetry
RUN pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false

RUN poetry install --no-interaction --no-ansi --no-root

COPY . .

# 🔥 execução direta
CMD ["python", "rodar_pipeline.py"]