name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: 📥 Checkout código
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 📦 Instalar Poetry
        run: |
          pip install poetry

      - name: 🔧 Configurar Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: 📥 Instalar dependências
        run: |
          poetry install

      - name: 🧪 Rodar testes DEV (data quality)
        run: |
          poetry run pytest -s tests/test_completude_mensal.py \
                               tests/test_quality_number_anual.py \
                               tests/test_variacao_mensal.py